Add new metric type: object
mozilla/glean_parser pull request #587
Opened 2023-06-05 15:37 UTC by badboy

This is the most bare-bones version for now.
It validates the `structure` and then generates the corresponding Rust code.

2024-01-22 19:02 UTC, chutten requested changes
Is the test that the yaml is parsed at all? Is there a test of the rust codegen?

2024-01-22 19:02 UTC, chutten commented on tests/data/object.yaml
> +    description: All threads' frame information.
```suggestion
    description: |
      All threads' frame information.
      e.g. `[{frames: [{module_index: 0, ip: "0xdecafc0ffe", trust: "scan"}]}]`
```

2024-02-09 14:25 UTC, travis79 approved these changes
Looks good to me, I guess we will add support for other languages as needed?

2024-02-12 09:40 UTC, badboy commented
> Looks good to me, I guess we will add support for other languages as needed?

yes. I'll file bugs.

2024-02-12 16:55 UTC, merged