Bug 1851999 - Prevent `ping` lifetime metrics on the `events` ping
mozilla/glean_parser pull request #625
Opened 2023-09-13 19:41 UTC by perrymcmanis144

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `make test` runs without emitting any warnings
  - `make lint` runs without emitting any errors
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
  - Any breaking changes to language binding APIs are noted explicitly

2023-09-13 19:50 UTC, perrymcmanis144 commented
hey @badboy here's a draft I'm working on. I figured this one looked like it needed to be solved in the python and not a schema so I did it that way.

just as a point of interest, I tried to run `make install-kotlin-linters` and this appears to require an explicit install of coreutils on mac.

2023-09-14 08:59 UTC, badboy commented
> just as a point of interest, I tried to run `make install-kotlin-linters` and this appears to require an explicit install of coreutils on mac.

probably because it uses `sha256sum`? We could change it to `shasum -a 256`

2023-09-14 09:11 UTC, badboy commented
Can we implement this as a lint? https://github.com/mozilla/glean_parser/blob/b03df4dbced33d84751135ecb34e9696332228d6/glean_parser/lint.py#L357

2023-09-14 13:57 UTC, perrymcmanis144 commented
> Can we implement this as a lint?
> 
> https://github.com/mozilla/glean_parser/blob/b03df4dbced33d84751135ecb34e9696332228d6/glean_parser/lint.py#L357

Sure, updated to reflect.

2023-09-15 10:54 UTC, badboy requested changes

2023-09-15 10:54 UTC, badboy commented on glean_parser/lint.py
> +            "Non-event metrics sent on the Events ping should have the ping lifetime"
We usually refer to them by their lowercase name.
```suggestion
            "Non-event metrics sent on the events ping should have the ping lifetime"
```

2023-09-15 10:54 UTC, badboy commented on tests/test_lint.py
> +    """Test that a `expires` dates too far in the future generates warnings"""
Copy-pasta. Needs an update.

2023-09-15 10:54 UTC, badboy commented on glean_parser/lint.py
> +        and metric.lifetime != metrics.Lifetime.ping
Wait, we want to _exclude_ ping-lifetime. `application` and user` lifetime are ok, these are static over time.

2023-09-15 10:54 UTC, badboy commented on glean_parser/lint.py
> +            "Non-event metrics sent on the Events ping should have the ping lifetime"
As said above, `ping` lifetime should be disallowed, `application` is what should be prefered.

2023-09-15 10:54 UTC, badboy commented on tests/test_lint.py
> +                    "lifetime": "application",
As said this should pass, `ping` should make it fail

2023-09-15 13:12 UTC, badboy requested changes
See inline comments for one.
There are more errors after that because in our test data we seem to have a couple of metrics that trigger that linter and thus now fail. The proper way is to make them use either another metric type in the test or set the correct lifetime

2023-09-15 13:12 UTC, badboy commented on glean_parser/lint.py
> +        and metric.type != metrics.Event
`metric.type` is a string, we can't compare that with a class.
```suggestion
        and metric.type != "event"
```

or (I think?)

```suggestion
        and not isinstance(metric, metrics.Event)
```

the former is more stringy, but IMO reads better

2023-09-15 13:42 UTC, badboy approved these changes

2023-09-15 13:54 UTC, merged